FROM node:20-alpine AS build
WORKDIR /frontend
COPY frontend/ .
RUN npm ci && npm run build

FROM nginx:alpine
COPY infra/docker/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /frontend/public /usr/share/nginx/html
