FROM python:3.11-slim
WORKDIR /app
COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY backend/app ./app
ENV DB_URL=mysql+pymysql://user:pass@mysql:3306/appstore
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
